version: '3.8'

services:
  backend:
    container_name: psicowise_backend
    image: ghcr.io/raphaelduarte/psicowise-backend:latest
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env