name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Definir variáveis de ambiente para testes
        run: |
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Build and run tests
        run: mvn clean test -Dspring.profiles.active=test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build .jar (sem rodar testes de novo)
        run: mvn clean package -DskipTests

      - name: Login no GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir e enviar a imagem para GHCR
        run: |
          docker build -t ghcr.io/psicowise/psicowise-backend:latest .
          docker push ghcr.io/psicowise/psicowise-backend:latest

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Construir e enviar a imagem para Docker Hub
        run: |
          docker build -t raphaelduartess/psicowise-backend:latest .
          docker push raphaelduartess/psicowise-backend:latest
      

      - name: Deploy na VPS via Webhook
        run: |
          curl -X POST "${{ secrets.EASYPANEL_DEPLOY_URL }}"

      - name: Aguardar e verificar deploy
        run: |
          echo "Aguardando 45 segundos para o deploy concluir..."
          sleep 120

          # Tentar até 5 vezes com intervalo de 10 segundos
          MAX_RETRIES=5
          RETRY_COUNT=0
          DEPLOY_SUCCESS=false

          while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ $DEPLOY_SUCCESS == false ]
          do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://psicowise-backend-v2.6qp1vk.easyp/health)
            if [ $HTTP_STATUS -eq 200 ]; then
              echo "✅ Deploy concluído com sucesso!"
              DEPLOY_SUCCESS=true
            else
              echo "⏳ Tentativa $((RETRY_COUNT+1))/$MAX_RETRIES: Endpoint ainda não disponível (status $HTTP_STATUS)"
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 10
            fi
          done

          if [ $DEPLOY_SUCCESS == false ]; then
            echo "❌ Deploy falhou: endpoint não está respondendo após múltiplas tentativas"
            exit 1
          fi