name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Definir variáveis de ambiente para testes
        run: |
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
      

      - name: Build and run tests
        run: mvn clean test -Dspring.profiles.active=test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build .jar (sem rodar testes de novo)
        run: mvn clean package -DskipTests

      - name: Login no GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir e enviar a imagem para GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/psicowise-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/psicowise-backend:latest

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.EASYPANEL_SSH_KEY }}
          script: |
            cd /home/deploy/psicowise
            git pull origin main
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GHCR_PAT }}
            docker-compose pull backend
            docker-compose up -d --build backend